app_user_home:
    path: /
    defaults:
      _controller: AppBundle:User:dashboard

app_user_pembayaran:
    path: /list-pembayaran
    defaults:
      _controller: AppBundle:User:listPembayaran

app_user_create_pembayaran:
    path: /create-pembayaran
    defaults:
      _controller: AppBundle:User:createPembayaran

app_user_profile:
    path: /profile
    defaults:
      _controller: AppBundle:User:profile

app_user_edit_profile:
    path: /edit-profile
    defaults:
      _controller: AppBundle:User:updateProfile

app_user_pemesanan:
    path: /list-pemesanan
    defaults:
      _controller: AppBundle:User:listPemesanan

app_user_update_pemesanan:
    path: /update-pemesanan
    defaults:
      _controller: AppBundle:User:updatePemesanan

app_user_delete_pembayaran:
    path: /delete-pembayaran
    defaults:
      _controller: AppBundle:User:deletePembayaran