app_admin_index:
    path: /
    defaults:
      _controller: AppBundle:Admin:index

app_admin_update_user:
    path: /update-user/{id}
    defaults:
      _controller: AppBundle:Admin:updateUser

app_admin_delete_user:
    path: /delete-user/{id}
    defaults:
      _controller: AppBundle:Admin:deleteUser

app_admin_list_pemesanan:
    path: /list-pemesanan
    defaults:
      _controller: AppBundle:Admin:getAllPemesanan

app_admin_delete_pemesanan:
    path: /delete-pemesanan/{id}
    defaults:
      _controller: AppBundle:Admin:deletePemesanan

app_admin_list_user:
    path: /list-user
    defaults:
      _controller: AppBundle:Admin:getAllUser

app_admin_list_barang:
    path: /list-barang
    defaults:
      _controller: AppBundle:Admin:getAllBarang

app_admin_create_barang:
    path: /create-barang
    defaults:
      _controller: AppBundle:Admin:createBarang

app_admin_delete_barang:
    path: /delete-barang/{id}
    defaults:
      _controller: AppBundle:Admin:deleteBarang

app_admin_update_barang:
    path: /update-barang/{id}
    defaults:
      _controller: AppBundle:Admin:updateBarang

app_admin_list_pembayaran:
    path: /list-pembayaran
    defaults:
      _controller: AppBundle:Admin:getAllPembayaran

app_admin_edit_confirm:
    path: /edit-confirm/{id}
    defaults:
      _controller: AppBundle:Admin:editConfirm

app_admin_delete_pembayaran:
    path: /delete-pembayaran/{id}
    defaults:
      _controller: AppBundle:Admin:deletePembayaran

app_admin_edit_proses:
    path: /edit-proses/{id}
    defaults:
       _controller: AppBundle:Admin:editProses