app_admin:
    resource: "@AppBundle/Resources/config/routing/routing_admin.yml"
    prefix: /admin

app_user:
    resource: "@AppBundle/Resources/config/routing/routing_user.yml"
    prefix: /user

app_home:
    resource: "@AppBundle/Resources/config/routing/routing_home.yml"
    prefix: /home

app_faq:
    path: /faq
    defaults:
      _controller: AppBundle:User:faq

app_barang_detail:
    path: /barang-detail/{id}
    defaults:
      _controller: AppBundle:User:barangDetail

app_gallery:
    path: /gallery
    defaults:
      _controller: AppBundle:User:gallery

app_gallery_page:
    path: /gallery/{page}
    defaults:
      _controller: AppBundle:User:gallery

app_cart:
    path: /cart
    defaults:
      _controller: AppBundle:User:cart

app_add_cart:
    path: /add-cart/{id}
    defaults:
      _controller: AppBundle:User:addCart

app_index:
    path: /
    defaults:
      _controller: AppBundle:Security:loginCheck

app_error:
    path: /error
    defaults:
      _controller: AppBundle:User:notification

app_success:
    path: /order-success
    defaults:
      _controller: AppBundle:User:success

app_product:
    path: /product
    defaults:
      _controller: AppBundle:User:product

app_register:
    path: /register
    defaults:
      _controller: AppBundle:User:register

app_pemesanan:
    path: /pemesanan
    defaults:
      _controller: AppBundle:User:createPemesanan

app_logout:
    path: /logout
