AppBundle\Entity\Pembayaran:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\PembayaranRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    manyToOne:
        user:
           targetEntity: User
           joinColumn:
                name: User
                referencedColumnName: id
                onDelete: "SET NULL"
    fields:
        namaPembayar:
            type: string
            length: 255
            column: nama_pembayar
        emailPembayar:
            type: string
            length: 255
            column: email_pembayar
        pembayaranBerkas:
            type: string
            length: 255
            column: pembayaran_berkas
        isConfirm:
            type: integer
            column: is_confirm
    lifecycleCallbacks: {  }
