AppBundle\Entity\Pemesanan:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\PemesananRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    manyToOne:
        user:
          targetEntity: User
          joinColumn:
            name: User
            referencedColumnName: id
            onDelete: "SET NULL"
        barang:
            targetEntity: Barang
            joinColumn:
                name: Barang
                referencedColumnName: id
                onDelete: "SET NULL"

    fields:
        totalPemesan:
            type: string
            length: 255
            column: total_pemesan
        totalHarga:
            type: string
            length: 255
            column: total_harga
        createdAt:
            type: datetime
            column: created_at
        isProses:
            type: integer
            column: is_proses    
    lifecycleCallbacks: {  }
