AppBundle\Entity\User:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        firstname:
            type: string
            length: 255
        lastname:
            type: string
            length: 255
        username:
            type: string
            length: 255
            unique: true
        email:
            type: string
            length: 255
        password:
            type: string
            length: 255
        address:
            type: string
            length: 255
        noTelp:
            type: string
            length: 255
            column: no_telp
        roles:
            type: text
    lifecycleCallbacks: {  }
